### ISSUE TITLE
see job postings

### ISSUE THREAD

**Issue by mpnsk** [mpnsk/xingedin#1]
as a user
I want to see all job postings on one page
so that I don't have to go to five different sites
and have a good overview

###### Todo
- [ ] #2
- [x] #4
###### not-yet-do
- [ ] display jobs in a uniform way
- [ ] save jobs and their searches on the server and/or client
- [ ] schedule searches
- [ ] notify on new jobs
